#!/usr/bin/env zsh

# Colours
BAD='\033[1;31m'
GOOD='\033[1;32m'
NEUTRAL='\033[0;36m'
INFO='\u001b[33m'
NONE='\033[0m'

# Constants
CODEPAD_DIR="`dirname "$0"`"
CONFIG_DIR="$HOME/.config/codepad"
TEMPLATES_DIR="$CODEPAD_DIR/templates"
NOW="`date "+%x_%X" | tr " " "_" | tr "/" "-"`"

# Setup configuration folder if it doesn't already exist
if ! [ -e "$CONFIG_DIR" ]
then
  mkdir -p "$CONFIG_DIR"
  echo "LAST_TEMPLATE=''" > "$CONFIG_DIR/last_template"
  echo "PAD_DIR='$HOME/pad'" > "$CONFIG_DIR/pad_dir"
fi

# Load configuration options
source "$CONFIG_DIR/pad_dir"
source "$CONFIG_DIR/last_template"

# Dynamic constants
AVAILABLE_TEMPLATES="`ls $TEMPLATES_DIR | grep -v / | tr '\n' ' '`"

if [ "$1" = "new" ]
then

  TEMPLATE="$2"
  NAME="$3"

  if [ -z "$TEMPLATE" ] || ! [ -e "$TEMPLATES_DIR/$TEMPLATE" ]
  then
    TEMPLATE="$LAST_TEMPLATE"
  fi

  if [ -z "$TEMPLATE" ] || ! [ -e "$TEMPLATES_DIR/$TEMPLATE" ]
  then
    echo "Error: template '$TEMPLATE' does not exist"
    exit 1
  fi

  if [ "$NAME" = "" ]
  then
    NAME="$NOW"
  fi

  NAME_DIR="$PAD_DIR/$NAME"

  if [ -e "$NAME_DIR" ]
  then
    mv "$NAME_DIR" "$NAME_DIR_$NOW" || exit 1
  fi

  cp -r "$TEMPLATES_DIR/$TEMPLATE" "$NAME_DIR" || exit 1
  cp -r $TEMPLATES_DIR/defaults/* "$NAME_DIR" || exit 1

  echo "$NAME_DIR"

elif [ "$1" = "clear" ]
then

  # Move codepad to /var/tmp
  BACKUP_DIR="/var/tmp/codepadbks"
  mkdir -p "$BACKUP_DIR"
  cd "$BACKUP_DIR"
  mv "$PAD_DIR" "$NOW"

  mkdir "$PAD_DIR"

  # Delete backups older than 3 days
  find . -maxdepth 1 -mindepth 1 -mtime +3 -exec rm -r {} +

elif [ "$1" = "build" ]
then

  ls in sol.* | entr -c sh -c "time node sol.js < in > out && echo -e '${GOOD}Succesful build!${NONE}'"

elif [ "$1" = "test" ]
then

  ls expect out | entr -c sh -c "git --no-pager diff expect out && echo -e '${GOOD}Correct answer!${NONE}'"

elif [ "$1" = "help" ]
then

  awk '/NAME/,EOF {print $0}' README.md | head -n -1

else

  echo "Error: unknown command"
  exit 1

fi

